/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.puc.gui.consultas.cadastros;

import br.com.puc.gui.EnumMsg;
import br.com.puc.gui.consultas.FrmEstadosConsultas;
import br.com.puc.gui.tablemodel.EstadoTableModel;
import br.com.puc.model.dao.table.Estado;
import javax.swing.JOptionPane;

/**
 *
 * @author 12647202
 */
public class FrmEstado extends javax.swing.JFrame {

    private String type;
    private FrmEstadosConsultas pai;
    private EstadoTableModel tableModel;
    Estado estado;

    /**
     * Creates new form IfrmEstado
     */
    public FrmEstado(FrmEstadosConsultas pai, EstadoTableModel tableModel, Estado est, String type) {
        initComponents();
        this.pai = pai;
        this.tableModel = tableModel;
        this.setType(type);
        this.estado = est;
        if (estado != null) {
            txtNome.setText(estado.getNomeEstado());
            txtSigla.setText(estado.getSiglaEstado());
        }
    }

    public void setType(String type) {
        this.type = type;
        btnAction.setText(type);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSigla = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSigla = new javax.swing.JTextField();
        btnAction = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblSigla.setText("Sigla:");

        lblNome.setText("Nome:");

        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });

        lblEstado.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNome)
                            .addComponent(lblSigla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtSigla)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lblEstado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnAction)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblEstado)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSigla)
                    .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnAction)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed

        if (type.equals(EnumMsg.Cadastrar.getmsg())) {
            if (tableModel.adicionar(new Estado(txtNome.getText(), txtSigla.getText()))) {
                JOptionPane.showOptionDialog(this, EnumMsg.CadastrarSucesso, EnumMsg.Cadastrar.getmsg(), JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
            } else {
                JOptionPane.showOptionDialog(this, EnumMsg.CadastrarErro.getmsg(), EnumMsg.Cadastrar.getmsg(), JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null);
            }
        } else if (type.equals(EnumMsg.Alterar.getmsg())) {
            estado.setNomeEstado(txtNome.getText());
            estado.setSiglaEstado(txtSigla.getText());
            if (tableModel.atualizar(estado)) {
                JOptionPane.showOptionDialog(this, EnumMsg.AlterarSucesso.getmsg(), EnumMsg.Alterar.getmsg(), JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
            } else {
                JOptionPane.showOptionDialog(this, EnumMsg.AlterarErro.getmsg(), EnumMsg.Alterar.getmsg(), JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null);
            }
        }

        estado = null;
        this.txtNome.setText("");
        this.txtSigla.setText("");

        //this.pai.refresh();
        pai = new FrmEstadosConsultas(pai.getPai());
        pai.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnActionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        this.pai.setVisible(true);
    }//GEN-LAST:event_formWindowClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSigla;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables
}
