/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.puc.gui.consultas;

import br.com.puc.gui.tablemodel.EnderecoTableModel;
import javax.swing.JFrame;

/**
 *
 * @author adelannucci
 */
public class FrmEnderecoConsultaFiltros extends javax.swing.JFrame {

    protected JFrame pai;
    protected EnderecoTableModel tableModel;
    
    /**
     * Creates new form FrmEnderecoConsultaFiltros
     */
    public FrmEnderecoConsultaFiltros(JFrame pai) {
        initComponents();
        this.tableModel = new EnderecoTableModel();
        this.pai = pai;
    }

    public JFrame getPai() {
        return pai;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
